In [1]:
import matplotlib as plt 
import numpy as np
import seaborn as sns
import plotly.express as px
import pandas as pd

#Reading Dataset

In [3]:
df=pd.read_csv(r"C:\Shila Data\DA-Project(Health_Care Real-World Data)\Healthcare_dataset.csv")

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,31-01-2024,Matthew Smith,Sons and Miller,Blue Cross,18856.281310,328,Urgent,02-02-2024,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,20-08-2019,Samantha Davies,Kim Inc,Medicare,33643.327290,265,Emergency,26-08-2019,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,22-09-2022,Tiffany Mitchell,Cook PLC,Aetna,27955.096080,205,Emergency,07-10-2022,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,18-11-2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,18-12-2020,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,19-09-2022,Kathleen Hanna,White-White,Aetna,14238.317810,458,Urgent,09-10-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,16-08-2020,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,15-09-2020,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,23-01-2020,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797310,316,Elective,01-02-2020,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,13-07-2020,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764720,347,Urgent,10-08-2020,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,25-05-2019,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092360,321,Elective,31-05-2019,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,02-04-2024,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,29-04-2024,Ibuprofen,Abnormal

#Data cleaning

In [5]:
df.shape

(55500, 15)

In [6]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [9]:
df.info

<bound method DataFrame.info of                     Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            31-01-2024     Matthew Smith               Sons and Miller
1            20-08-2019   Samantha Davies                       Kim Inc
2            22-09-2022  Tiffany Mitchell                      Cook PLC
3            18-11-2020       Kevin Wells    Hernandez Rogers and Vang,
4            19-09-2022    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        16-08-2020     Joshua Jarvis                Jones-Thompson
55496        23-01-2020   Taylor Sullivan                  Tucker-Moyer
55497        13-07-2020    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        25-05-2019    Kimberly Curry      Jackson Todd and Castro,
55499        02-04-2024     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281310          328         Urgent
1               Medicare    33643.327290          265      Emergency
2                  Aetna    27955.096080          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317810          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797310          316       Elective
55497   UnitedHealthcare    27620.764720          347         Urgent
55498           Medicare    32451.092360          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         02-02-2024  Paracetamol        Normal
1         26-08-2019    Ibuprofen  Inconclusive
2         07-10-2022      Aspirin        Normal
3         18-12-2020    Ibuprofen      Abnormal
4         09-10-2022   Penicillin      Abnormal
...              ...          ...           ...
55495     15-09-2020   Penicillin      Abnormal
55496     01-02-2020      Aspirin        Normal
55497     10-08-2020    Ibuprofen      Abnormal
55498     31-05-2019    Ibuprofen      Abnormal
55499     29-04-2024    Ibuprofen      Abnormal

[55500 rows x 15 columns]>

#checking null values

In [12]:
df.isna()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

#checking duplicates

In [16]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Length: 55500, dtype: bool

In [17]:
df.duplicated().sum()

534

In [19]:
df.head(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,31-01-2024,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,02-02-2024,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,20-08-2019,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,26-08-2019,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,22-09-2022,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,07-10-2022,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,18-11-2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,18-12-2020,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,19-09-2022,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,09-10-2022,Penicillin,Abnormal

In [20]:
df["Name"]

0            Bobby JacksOn
1             LesLie TErRy
2              DaNnY sMitH
3             andrEw waTtS
4            adrIENNE bEll
               ...
55495    eLIZABeTH jaCkSOn
55496           KYle pEREz
55497         HEATher WaNG
55498       JENniFER JOneS
55499         jAMES GARCiA
Name: Name, Length: 55500, dtype: object

#Data validation

In [24]:
df["Name"]=df["Name"].str.title()

In [25]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,31-01-2024,Matthew Smith,Sons and Miller,Blue Cross,18856.281310,328,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,20-08-2019,Samantha Davies,Kim Inc,Medicare,33643.327290,265,Emergency,26-08-2019,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,22-09-2022,Tiffany Mitchell,Cook PLC,Aetna,27955.096080,205,Emergency,07-10-2022,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,18-11-2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,18-12-2020,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,19-09-2022,Kathleen Hanna,White-White,Aetna,14238.317810,458,Urgent,09-10-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,16-08-2020,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,15-09-2020,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,23-01-2020,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797310,316,Elective,01-02-2020,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,13-07-2020,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764720,347,Urgent,10-08-2020,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,25-05-2019,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092360,321,Elective,31-05-2019,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,02-04-2024,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,29-04-2024,Ibuprofen,Abnormal

In [26]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,31-01-2024,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,20-08-2019,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,26-08-2019,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,22-09-2022,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,07-10-2022,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,18-11-2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,18-12-2020,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,19-09-2022,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,09-10-2022,Penicillin,Abnormal